name: Main Pipeline
on:
  push:

jobs:
  call-template:
    uses: org/kk789kk856-cmyk/test/.github/workflows/check_deploy.yml@main
    with:
      branch: ${{ github.ref }}
      event_name: ${{ github.event_name }}
